### ISSUE TITLE
FX script causes crash in Ingestor.py

### ISSUE THREAD

**Issue by kerelukej** [MetPX/Sundew#12]
A FX script was causing Ingestor.py to crash:
```
Traceback (most recent call last):
  File "/usr/bin/pxFilter", line 147, in <module>
    filter.ingestor.ingestBulletinFile(igniter)
  File "/usr/lib/px/Ingestor.py", line 657, in ingestBulletinFile
    bullManager.writeBulletinToDisk(data[index], True, True)
  File "/usr/lib/px/bulletinManager.py", line 207, in writeBulletinToDisk
    self.source.ingestor.ingest(tempNom, nomFichier, clist)
  File "/usr/lib/px/Ingestor.py", line 301, in ingest
    os.link(dbName, clientQueueName)
UnboundLocalError: local variable 'clientQueueName' referenced before assignment
```
Investigation showed that 'clientQueueName' was being referenced before assignment. (go figure).  Corrected code and tested successfully.

Here are the changes:
`lib/Ingestor.py`

Line 296 - 305

**original**
```
        for name in feedNames:
            if name in clientNames : continue
            sourceQueueName = PXPaths.RXQ + name + '/' + ingestName
            self.createDir(os.path.dirname(sourceQueueName), self.clientDirsCache)
            try:
                os.link(dbName, clientQueueName)
            except OSError:
                (type, value, tb) = sys.exc_info()
                self.logger.error("Unable to link to client queue %s %s, Type: %s, Value: %s" % (dbName, clientQueueName, type, value))
            #os.link(dbName, sourceQueueName)
```
**changed**
```
        for name in feedNames:
            if name in clientNames : continue
            sourceQueueName = PXPaths.RXQ + name + '/' + ingestName
            self.createDir(os.path.dirname(sourceQueueName), self.clientDirsCache)
            try:
                os.link(dbName, sourceQueueName)
            except OSError:
                (type, value, tb) = sys.exc_info()
                self.logger.error("Unable to link to client queue %s %s, Type: %s, Value: %s" % (dbName, sourceQueueName, type, value))
            #os.link(dbName, sourceQueueName)
```

or changed `clientQueueName` to `sourceQueueName` on lines 301 and 304

**Comment by petersilva** [comment]
We can accept a patch, if you make one and do a pull request.  Steps:

```
git checkout https://github.com/MetPX/Sundew
cd Sundew
git branch issue12
git checkout issue12
vi Ingestor.py
git commit Ingestor.py -m "use SourceQueueName, not client one."
git push
git push origin issue12

```
then make a pull request on github (only know how to do that from web page.)

**Comment by petersilva** [comment]
the first *git push* is probably not needed or helpful.

**Comment by petersilva** [comment]
@kerelukej fixed this sep 26th, 2019... so closing.
